### ISSUE TITLE
Hey can we get in touch

### ISSUE THREAD

**Issue by didair** [rylandg/myos#10]
Hey Rylan! Can we get in touch? I noticed you invited me to collaborate on this project, if it was a mistake - don't sweat it, i won't accept it and I won't harm this project in any way.

**Comment by rylandg** [comment]
Not a bug at all. Anyone is welcome to make a contribution. Only rule currently, 

**Code checked into master must have at least 1 review**

Feel free to message me via my email rylandgoldstein@gmail.com or dm me on twitter https://twitter.com/taillogs

**Comment by didair** [comment]
Aah sorry! I misread the invitation and thought it would give me owner permissions :D
