### ISSUE TITLE
Script does not work in Ubuntu

### ISSUE THREAD

**Issue by marcopiraccini** [rylandg/myos#13]
**Describe the bug**
When running in Ubutntu, `myos.sh` does not work: 

⇒ ./myos.sh init  
/bin/sh: 0: Illegal option - 

The reason is probably that in ubuntu `/bin/sh` is a link to `dash`:

```
⇒ ls -lah /bin/sh
lrwxrwxrwx 1 root root 4 gen 14 11:37 /bin/sh -> dash*
```
One solution would be to use `bash`  in the script or adapt the script to work also with `dash`

**To Reproduce**
Just run in Ubuntu 19.04 should be the same in other versions) 

**Expected behavior**
It should not exit immediately :)

**Host OS (please complete if relevant):**
 - Ubuntu 19.04, but any recent Ubuntu should behave the same

**Comment by tokelove** [comment]
I can reproduce this on Ubuntu 18.04

**Comment by rylandg** [comment]
Will fix today. It’s actually just a single character messing it up.

**Comment by rylandg** [comment]
Should be fixed by https://github.com/rylandg/myos/pull/14 please let me know!

**Comment by marcopiraccini** [comment]
It's fixed, tnx :)
