### ISSUE TITLE
Comment myos.sh

### ISSUE THREAD

**Issue by dimensi0n** [rylandg/myos#16]
I was trying to take a look at myos.sh, the code is clean and readable but not easy to understand for beginners.

That's why I suggest commenting on every part of this file to make it easier to understand.

If you want I can do it and open a pull request.

**Comment by rylandg** [comment]
I would love that!

I'm actually surprised it was clean and readable because I suck at shell scripting. Go ahead and send me a pull request and I'll review it right away.

**Comment by rylandg** [comment]
@all-contributors please add @dimensi0n for improved documentation and comments

**Comment by dimensi0n** [comment]
I made my pull request #25
