### ISSUE TITLE
Fail to run the container, with docker-compose version 3.7

### ISSUE THREAD

**Issue by muniter** [rylandg/myos#27]
**Describe the bug**
`myos create rysenv` fails because the generated `docker-compose` file is not supported by docker-compose. myos.sh generates `version: "3.7"`. 

**To Reproduce**
Follow the installation steps until you get to `$ myos create rysenv` then the problem arises

**Expected behavior**
The container runs succesfully

**Host OS:**
- Ubuntu 18.04
- Docker version 18.09.6, build 481bc77
- docker-compose version 1.17.1. 

**Additional context**
Fixed it by changing `version: "3.7"` by `version: "3"` and then running `docker-compose up -d` and renaming the container for what `myos.sh` was looking for `docker container rename mayosconfig_myos_1 rysenv_myos_1`

**Comment by rylandg** [comment]
Hey, thanks for opening the issue. Just to help me understand, could this be solved by updating docker-compose runtime? We don't exactly "generate" a docker-compose.yml file, it's just a template. Maybe we can get away with a much lower version, let me look into it.

**Comment by rylandg** [comment]
@all-contributors please add @muniter for finding bugs

**Comment by muniter** [comment]
Hey, you're welcome, glad to be of help.

> Maybe we can get away with a much lower version, let me look into it.

From what I've just read seems like yeah, we can manage by running a much lower docker-compose file version. Just looking at the file is pretty simple, and version 3 supports all the features being used.

The following [article](https://docs.docker.com/compose/compose-file/compose-versioning/#version-3) the differences in version **3.x** are named, none should affect what's being used. I think is a better idea to set it to version **3** and have a wider scope. Ubuntu 18.04 is one of the must run distro in developers that run Linux I would imagine. So supporting them out of the box would be great.

**Comment by rylandg** [comment]
Sounds 100% logical. Want to make the PR or should I?

**Comment by muniter** [comment]
@rylandg  Great! go ahead with the PR. I'm just getting started with git, don't know how to do a PR yet :D. And a little busy today.

 Just a geek from an unrelated profession getting into linux, programming, docker, etc.

**Comment by muniter** [comment]
Oh I managed to do It using the gui nvm. PR submitted #32
