### ISSUE TITLE
No feedback/error when repo is missing

### ISSUE THREAD

**Issue by wrenchpilot** [rylandg/myos#8]
**No feedback/error when repo is missing**
myos create foo does not return an error or fail if the repo is missing.  It just runs forever.  Running docker-compose up -d by hand returns:

Pulling myos (myos:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling myos (myos:latest)...
ERROR: pull access denied for myos, repository does not exist or may require 'docker login'

**To Reproduce**
1. install myos via npm
2. init the template
3. run myos create foo
4. the command will run until interrupted.  I let it run for over an hour before I killed it.

**Host OS (please complete if relevant):**
 - OS: macOS
 - Version 10.14.5

**Comment by wrenchpilot** [comment]
Was able to get past this by editing the docker-compose.yml file and changing the image from:
image: 'myos:${TAG:-latest}'

to 

image: 'rylandg/myos'

**Comment by rylandg** [comment]
Awesome feedback. Definitely an issue. Short term I will simply put out a patch that relies on the remote image.

**Comment by wrenchpilot** [comment]
Awesome project, if I catch a break I'll see if I can submit some pulls for other editors etc 🙏

**Comment by rylandg** [comment]
Would definitely appreciate it. I prefer code reviews always, when possible. If you have a moment, check this out https://github.com/rylandg/myos/pull/9. If you check it real quick, i'll merge it in a few.

**Comment by rylandg** [comment]
Fixed in https://github.com/rylandg/myos/pull/9
